# SPDX-License-Identifier: CC0-1.0
# Adapted from Alexey Salmin's ov08x40 libcamera simple-pipeline tuning.
%YAML 1.1
---
version: 1
algorithms:
  - BlackLevel:
  - Awb:
  - Ccm:
      ccms:
        - ct: 6500
          ccm: [ 1.0294, 0.0000, 0.0000,
                 0.0000, 0.9621, 0.0000,
                 0.0000, 0.0000, 1.2892 ]
  - Adjust:
  - Agc:
...
